USE FSQ3_Lawrence_Shop
GO
INSERT INTO Products(ProductId, CategoryId, Name, ImageFileName, UnitCost, Description, IsDownload)
VALUES ('ThEs01','30', 'Thunder Espresso 01','es01.jpg','0.97', 'A blend of pure and lightly roasted Arabica from South America, the Thunder Espresso 01 capsule reveals sweet and biscuit flavours, reinforced by a little acidity and a fruity note.','False'),
('ThEs02','30', 'Thunder Espresso 02','es02.jpg','0.97', 'A new blend of East African, Central and South American Arabicas which has been lightly roasted to create a delicate and balanced marriage of lightly toasted cereal and fruity notes.','False'),
('ThEs03','30', 'Thunder Espresso 03','es03.jpg','0.97', 'Blending South American Arabicas with a touch of Robusta, the Thunder Espresso 03 capsule is an espresso with a rich aroma and a strong typical cereal note.','False'),
('ThEs04','30', 'Thunder Espresso 04','es04.jpg','0.97', 'This blend of Central and South American Arabicas is medium roast to bring out a round and very balanced bouquet. It evokes the scent of freshly toasted coffee escaping from the roaster. Roasted and caramelized notes.','False'),
('ThEs05','30', 'Thunder Espresso 05','es05.jpg','0.97', 'Thunder Esspreoss 05 is a coffee elaborated on a base of Livanto Grand Cru. A bled of Arabicas from South and Central America with a round and very blanaced bouquet. The sweet flavor of caramel softens the roasted notes.','False'),
('ThEs06','30', 'Thunder Espresso 06','es06.jpg','0.97', 'The balance of lightly roasted South and Central American Arabicas with Robusta gives this capsules sweet and woody notes and a full lasting taste on the palate.','False'),
('ThEs07','30', 'Thunder Espresso 07','es07.jpg','0.97', 'A dark roast of pure South and Central American Arabicas the Thunder Espresso 07 capsule has a strong character and intense body enhanced by cocoa notes.','False'),
('ThEs08','30', 'Thunder Espresso 08','es08.jpg','0.97', 'A blend of South American and East African Arabicas with a touch of Robusta roasted separately to create the subtle fruity note of this full bodied intense espresso.','False'),
('ThEs09','30', 'Thunder Espresso 09','es09.jpg','0.97', 'This blend of washed Arabicas from Latin America and Asia fully unveils its character thanks to the technique of long roasting at a low temperature. Its powerful personality reveals intense roasted notes together with hints of bitter cocoa powder and toasted cereals that express themselves in a silky and velvety texture.','False'),
('ThEs10','30', 'Thunder Espresso 10','es10.jpg','1.13', 'A daring blend of two Robustas from Brazil and Guatemala and a separately roasted Arabica from South America. Thunder Espresso 10 is a coffee capsule of exceptional intensity. Its powerful bitterness and notes of pepper are balanced by a full and creamy texture.','False'),
('ThEs11','30', 'Thunder Espresso 11','es11.jpg','1.13', 'This 100% Arabica coffee comes exclusively from the Harrar region. With its notes of ripe fruits fresh flowers and malty cereal. This medium bodied espresso boasts a remarkably velvety body and can be extracted and enjoyed.','False'),
('ThEs12','30', 'Thunder Espresso 12','es12.jpg','1.13', 'Robusta Uganda contains 100% Robusta coffee from Uganda. This coffee is surprisingly fine and sweet for a Robusta with undeniable intense rich cocoa notes.','False'),
('ThBl01','31', 'Thunder Blend 01','bl01.jpg','1.13', 'This delicate coffee expresses a floral bouquet reminiscent of jasmine white lily bergamot and orange blossom together with notes of wood. A pure Arabica blend composed of two very different coffees coming from the birthplace of coffee Ethiopia.','False'),
('ThBl02','31', 'Thunder Blend 02','bl02.jpg','1.13', 'This is Ethiopian Arabica at its finest decadently aromatic. It has an orange blossom aroma but the rich fruit jam notes come from the sundried coffee in Master Origin Ethiopia with dry processed Arabica. Continually hand turning the coffee cherry to ensure even drying calls for great care. And Ethiopian farmers have used this method for longer than anyone else.','False'),
('ThBl03','31', 'Thunder Blend 03','bl03.jpg','1.13', 'If Black Honey processing were the easy road to a nectarous coffee all do it. But only a few farmers dare. It is a rare process because it calls for meticulous monitoring. Master Origin Thunder Blend 03 with Black Honey processed Arabica contains this coffee. It gives this Arabica its smooth honeyed texture and sweet cereal notes.','False'),
('ThBl04','31', 'Thunder Blend 04','bl04.jpg','1.13', 'Master Origin Thunder Blend 04 with Late Harvest uses only high grown washed processed Colombian Arabica. Can you taste the lively acidity and the burst of winey red fruit aromas. That comes from those coffee farmers who dared to wait longer before harvesting their crop.','False'),
('ThBl05','31', 'Thunder Blend 05','bl05.jpg','1.13', 'Master Origin Thunder Blend 05 wet hulled Arabica is a race against rain. Sumatran farmers wet-hull their coffee because of the humid climate. They remove the parchment when the coffee is soft and moist because exposed beans dry faster. The method is unique to them and produces the classic Indonesian taste. Velvety thick, wildly aromatic with notes of cured tobacco.','False'),
('ThBl06','31', 'Thunder Blend 06','bl06.jpg','1.13', 'Master Origin Thunder Blend 06 with Robusta Monsoon gets its intense woody spicy aromatics from the monsooned Robusta blended into Indian Arabica. Monsooning coffees is unique to Indias southwest coast. Months of monsoonal winds repeatedly swell and dry the beans. It mimics the journey it used to take when sailing to Europe.','False');


